insert into books (title, author, price) values ('The Great Gatsby', 'Emily Brown', 19.74);
insert into books (title, author, price) values ('The Great Gatsby', 'Emily Brown', 27.8);
insert into books (title, author, price) values ('1984', 'John Smith', 17.03);
insert into books (title, author, price) values ('The Great Gatsby', 'John Smith', 39.42);
insert into books (title, author, price) values ('1984', 'David Wilson', 8.09);
insert into books (title, author, price) values ('1984', 'Sarah Davis', 43.72);
insert into books (title, author, price) values ('The Great Gatsby', 'John Smith', 43.41);
insert into books (title, author, price) values ('The Great Gatsby', 'Sarah Davis', 8.18);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'Sarah Davis', 22.63);
insert into books (title, author, price) values ('The Catcher in the Rye', 'John Smith', 18.98);
insert into books (title, author, price) values ('The Great Gatsby', 'Michael Johnson', 27.38);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'John Smith', 12.91);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'Emily Brown', 17.57);
insert into books (title, author, price) values ('The Catcher in the Rye', 'Sarah Davis', 19.28);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'David Wilson', 18.39);
insert into books (title, author, price) values ('Pride and Prejudice', 'Sarah Davis', 12.3);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'Michael Johnson', 44.4);
insert into books (title, author, price) values ('The Great Gatsby', 'Emily Brown', 47.29);
insert into books (title, author, price) values ('1984', 'David Wilson', 32.78);
insert into books (title, author, price) values ('Pride and Prejudice', 'Michael Johnson', 25.9);
insert into books (title, author, price) values ('The Great Gatsby', 'David Wilson', 42.17);
insert into books (title, author, price) values ('To Kill a Mockingbird', 'Emily Brown', 16.02);
insert into books (title, author, price) values ('The Catcher in the Rye', 'Michael Johnson', 14.79);
insert into books (title, author, price) values ('The Catcher in the Rye', 'Sarah Davis', 11.84);
insert into books (title, author, price) values ('The Great Gatsby', 'Emily Brown', 21.96);